using System.Numerics;
using Content.Client._CE.ZLevels.Core; // Mono
using Content.Shared._CE.Planets.Descent; // CE
using Content.Shared._CE.ZLevels.Core.Components; // Mono
using Content.Shared._Mono.Company;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Map;
using Robust.Shared.Physics.Components;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility; // CE

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class NavScreen : BoxContainer
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IGameTiming _timing = default!; // CE
    private SharedTransformSystem _xformSystem;
    private CEClientZLevelsSystem _zLevels; // Mono

    private EntityUid? _consoleEntity; // Entity of controlling console
    private EntityUid? _shuttleEntity;

    // CE: planet descent request (fired once the hold-to-target completes)
    public event Action<NetEntity>? OnDescendRequest;

    public NavScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _xformSystem = _entManager.System<SharedTransformSystem>();
        _zLevels = _entManager.System<CEClientZLevelsSystem>(); // Mono

        IFFToggle.OnToggled += OnIFFTogglePressed;
        IFFToggle.Pressed = NavRadar.ShowIFF;

        IFFShuttleToggle.OnToggled += OnIFFShuttleTogglePressed;
        IFFShuttleToggle.Pressed = NavRadar.ShowIFFShuttles;

        DockToggle.OnToggled += OnDockTogglePressed;
        DockToggle.Pressed = NavRadar.ShowDocks;

        NavRadar.OnPlanetClick += OnPlanetClicked; // CE

        NfInitialize(); // Frontier Initialization for the NavScreen
    }

    // Frontier - IFF search
    private void OnIffSearchChanged(string text)
    {
        text = text.Trim();

        NavRadar.IFFFilter = text.Length == 0
            ? null // If empty, do not filter
            : (entity, grid, iff, hideLabel, name) => // Otherwise use simple search criteria
            {
                // Check entity name
                if (name.Contains(text, StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
                if (hideLabel)
                    return false;

                // Check company name
                if (_entManager.TryGetComponent<CompanyComponent>(entity, out var companyComp) &&
                    !string.IsNullOrEmpty(companyComp.CompanyName))
                {
                    // Try to match the company ID directly
                    if (companyComp.CompanyName.Id.Contains(text, StringComparison.OrdinalIgnoreCase))
                    {
                        return true;
                    }

                    // Try to match company name from prototype
                    if (_prototypeManager.TryIndex(
                        companyComp.CompanyName, out var prototype) &&
                        prototype.Name.Contains(text, StringComparison.OrdinalIgnoreCase))
                    {
                        return true;
                    }
                }

                return false;
            };
    }

    public void SetShuttle(EntityUid? shuttle)
    {
        _shuttleEntity = shuttle;

        NfAddShuttleDesignation(shuttle); // Frontier - PR #1284 Add Shuttle Designation
    }

    public void SetConsole(EntityUid? console)
    {
        _consoleEntity = console;
        NavRadar.SetConsole(console);
    }

    // CE: fired by the radar once the pilot has held the click on a planet for the
    // full targeting duration. No popups — the console status line shows the state.
    private void OnPlanetClicked(EntityUid planet)
    {
        OnDescendRequest?.Invoke(_entManager.GetNetEntity(planet));
    }

    private void OnIFFTogglePressed(BaseButton.ButtonEventArgs args)
    {
        NavRadar.ShowIFF ^= true;
        args.Button.Pressed = NavRadar.ShowIFF;
    }

    private void OnIFFShuttleTogglePressed(BaseButton.ButtonEventArgs args)
    {
        NavRadar.ShowIFFShuttles ^= true;
        args.Button.Pressed = NavRadar.ShowIFFShuttles;
    }

    private void OnDockTogglePressed(BaseButton.ButtonEventArgs args)
    {
        NavRadar.ShowDocks ^= true;
        args.Button.Pressed = NavRadar.ShowDocks;
    }

    public void UpdateState(NavInterfaceState scc)
    {
        NavRadar.UpdateState(scc);

        // Update port names if custom names are available
        UpdateNetworkPortButtonNames(scc.NetworkPortNames);

        NfUpdateState(); // Frontier Update State
    }

    /// <summary>
    /// Updates the text on the network port buttons based on the custom port names.
    /// </summary>
    /// <param name="portNames">Dictionary of port IDs to display names</param>
    private void UpdateNetworkPortButtonNames(Dictionary<string, string> portNames)
    {
        // Map of button names to their corresponding port IDs in the component
        var buttonToPortIdMap = new Dictionary<Button, string>
        {
            { DeviceButton1, "device-button-1" },
            { DeviceButton2, "device-button-2" },
            { DeviceButton3, "device-button-3" },
            { DeviceButton4, "device-button-4" },
            { DeviceButton5, "device-button-5" },
            { DeviceButton6, "device-button-6" },
            { DeviceButton7, "device-button-7" },
            { DeviceButton8, "device-button-8" }
        };

        // For each button, check if there's a custom name and update accordingly
        foreach (var (button, portId) in buttonToPortIdMap)
        {
            if (portNames.TryGetValue(portId, out var customName))
            {
                // Use the custom name if available
                button.Text = customName;
            }
            else
            {
                // Otherwise use the default localized name
                var locKey = $"shuttle-console-{portId}";
                button.Text = Loc.GetString(locKey);
            }
        }
    }

    public void SetMatrix(EntityCoordinates? coordinates, Angle? angle)
    {
        _shuttleEntity = coordinates?.EntityId;
        NavRadar.SetMatrix(coordinates, angle);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (!_entManager.TryGetComponent(_shuttleEntity, out TransformComponent? gridXform) ||
            !_entManager.TryGetComponent(_shuttleEntity, out PhysicsComponent? gridBody))
        {
            return;
        }

        var (_, worldRot, worldMatrix) = _xformSystem.GetWorldPositionRotationMatrix(gridXform);
        var worldPos = Vector2.Transform(gridBody.LocalCenter, worldMatrix);

        // Mono - remap to [0, 360)
        var displayRot = (-worldRot).Reduced();
        var displayRotDegrees = displayRot.FlipPositive().Degrees;

        GridPosition.Text = Loc.GetString("shuttle-console-position-value",
            ("X", $"{worldPos.X:0.0}"),
            ("Y", $"{worldPos.Y:0.0}"));
        GridOrientation.Text = Loc.GetString("shuttle-console-orientation-value",
            ("angle", $"{displayRotDegrees:0.0}"));

        var gridVelocity = gridBody.LinearVelocity;
        gridVelocity = displayRot.RotateVec(gridVelocity);
        // Get linear velocity relative to the console entity
        GridLinearVelocity.Text = Loc.GetString("shuttle-console-linear-velocity-value",
            ("X", $"{gridVelocity.X + 10f * float.Epsilon:0.0}"),
            ("Y", $"{gridVelocity.Y + 10f * float.Epsilon:0.0}"));
        GridAngularVelocity.Text = Loc.GetString("shuttle-console-angular-velocity-value",
            ("angularVelocity", $"{-MathHelper.RadiansToDegrees(gridBody.AngularVelocity) + 10f * float.Epsilon:0.0}"));

        UpdateAltitude(gridXform); // Mono
    }

    // Mono: z-level altimeter
    private void UpdateAltitude(TransformComponent gridXform)
    {
        float? altitude = null;
        string? state = null;

        if (gridXform.MapUid is { } mapUid && _shuttleEntity is { } shuttle)
        {
            var onTransit = _entManager.HasComponent<CEZTransitMapComponent>(mapUid);

            if (onTransit || _entManager.HasComponent<CEZMapComponent>(mapUid))
                altitude = _zLevels.GetAbsoluteAltitude(shuttle);

            // The liftoff spool countdown outranks Flying: it's the ground-layer
            // z-hop spool (see CEZLevelsSystem.PilotControl), not the ascent breach —
            // that one renders from the networked charge/warning timestamps below.
            if (_entManager.TryGetComponent(shuttle, out CEZPhysicsComponent? spoolPhys) &&
                spoolPhys.LaunchCountdown > 0f)
            {
                state = Loc.GetString("shuttle-console-travel-state-launching",
                    ("countdown", $"{spoolPhys.LaunchCountdown:0.0}"));
            }
            else if (onTransit)
            {
                state = Loc.GetString("shuttle-console-travel-state-flying");
            }
            else if (altitude != null)
            {
                state = Loc.GetString(_entManager.HasComponent<CEZGroundLayerComponent>(mapUid)
                    ? "shuttle-console-travel-state-grounded"
                    : "shuttle-console-travel-state-hovering");
            }
        }

        // CE: descent/ascent status trumps everything else. Charging counts down the
        // console spinup (descent) or the breach charge (ascent — the ship is climbing
        // the open-sky gap, a transit map, which would otherwise read Flying);
        // Launching counts down the ascent telegraph; Descending holds from the drop
        // through the warp until the sequence concludes (the grid rides a pseudo-map /
        // transit mid-sequence, which would otherwise read as Hovering/Flying).
        // All of these render client-side off networked timestamps.
        if (_shuttleEntity is { } shuttleUid)
        {
            if (_entManager.TryGetComponent(shuttleUid, out CEDescentSpinupComponent? spinup))
            {
                var remaining = Math.Max(0.0, (spinup.End - _timing.CurTime).TotalSeconds);
                state = Loc.GetString("shuttle-console-travel-state-charging",
                    ("countdown", $"{remaining:0.0}"));
            }
            else if (_entManager.HasComponent<CEDescentComponent>(shuttleUid))
            {
                state = Loc.GetString("shuttle-console-travel-state-descending");
            }
            else if (_entManager.TryGetComponent(shuttleUid, out CEAscentWarningComponent? ascentWarning))
            {
                var remaining = Math.Max(0.0, (ascentWarning.End - _timing.CurTime).TotalSeconds);
                state = Loc.GetString("shuttle-console-travel-state-launching",
                    ("countdown", $"{remaining:0.0}"));
            }
            else if (_entManager.TryGetComponent(shuttleUid, out CEAscentChargeComponent? ascentCharge))
            {
                var remaining = Math.Max(0.0, (ascentCharge.End - _timing.CurTime).TotalSeconds);
                state = Loc.GetString("shuttle-console-travel-state-charging",
                    ("countdown", $"{remaining:0.0}"));
            }
            else if (_entManager.TryGetComponent(shuttleUid, out CEDescentStunnedComponent? stunned))
            {
                var remaining = Math.Max(0.0, (stunned.End - _timing.CurTime).TotalSeconds);
                state = Loc.GetString("shuttle-console-travel-state-stunned",
                    ("countdown", $"{remaining:0.0}"));
            }
        }

        // CE: while the pilot is holding the click on a planet, show the targeting
        // countdown instead.
        if (NavRadar.TargetingRemaining is { } targeting)
        {
            state = Loc.GetString("shuttle-console-travel-state-targeting",
                ("countdown", $"{targeting:0.0}"));
        }

        var onZNetwork = altitude != null;
        GridAltitudeCaption.Visible = onZNetwork;
        GridAltitude.Visible = onZNetwork;
        GridVerticalVelocityCaption.Visible = onZNetwork;
        GridVerticalVelocity.Visible = onZNetwork;

        var stateText = state ?? Loc.GetString("shuttle-console-travel-state-hovering");
        var stateMsg = FormattedMessage.FromMarkupPermissive(stateText);
        GridTravelState.Text = stateMsg.ToString();
        GridTravelState.FontColorOverride = FirstMarkupColor(stateMsg) ?? Color.FromHex("#00ff2a");

        if (!onZNetwork)
            return;

        GridAltitude.Text = Loc.GetString("shuttle-console-altitude-value",
            ("altitude", $"{altitude!.Value:0.00}"));

        var vertical = 0f;
        if (_entManager.TryGetComponent(_shuttleEntity, out CEZPhysicsComponent? velPhys))
            vertical = velPhys.Velocity;
        GridVerticalVelocity.Text = Loc.GetString("shuttle-console-vertical-velocity-value",
            ("velocity", $"{vertical + 10f * float.Epsilon:0.00}"));
    }

    /// <summary>
    /// CE: returns the first [color=...] value in a parsed message, if any.
    /// </summary>
    private static Color? FirstMarkupColor(FormattedMessage message)
    {
        foreach (var node in message.Nodes)
        {
            if (node is { Closing: false, Name: "color" } && node.Value.ColorValue is { } color)
                return color;
        }

        return null;
    }
}
