using System.Linq;
using System.Numerics;
using Content.Client._Mono.Radar;
using Content.Client.Station; // Frontier
using Content.Shared._CE.Planets;
using Content.Shared._CE.Planets.Descent;
using Content.Shared._CE.ZLevels.Core.EntitySystems;
using Content.Shared._Crescent.ShipShields;
using Content.Shared._Mono.Company;
using Content.Shared._Mono.Detection;
using Content.Shared._Mono.Radar;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Content.Shared.Shuttles.Systems;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Physics;
using Robust.Shared.Physics.Collision.Shapes;
using Robust.Shared.Physics.Components;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
[Virtual]
public partial class ShuttleNavControl : BaseShuttleControl // Mono
{
    [Dependency] private IMapManager _mapManager = default!;
    [Dependency] private IUserInterfaceManager _uiManager = default!;
    private readonly DetectionSystem _detection; // Mono
    private readonly StationSystem _station; // Frontier
    private readonly SharedShuttleSystem _shuttles;
    private readonly SharedTransformSystem _transform;
    private readonly RadarBlipsSystem _blips;
    private readonly CESharedZLevelsSystem _zLevels; // CE

    /// <summary>
    /// Used to transform all of the radar objects. Typically is a shuttle console parented to a grid.
    /// </summary>
    protected EntityCoordinates? _coordinates; // Mono

    /// <summary>
    /// Entity of controlling console
    /// </summary>
    protected EntityUid? _consoleEntity; // Mono

    // Mono - is world rotation of the view.
    protected Angle? _rotation = Angle.Zero;

    private Dictionary<NetEntity, List<DockingPortState>> _docks = new();

    // temporary buffers to avoid per-frame heap churn
    private readonly List<BlipData> _tempBlipDataList = new();
    private readonly HashSet<EntityUid> _visibleGridsSet = new();
    private static readonly Vector2[] RadarPosVertsCache =
    [
        new Vector2(0f, -2f),
        new Vector2(1f, 0f),
        new Vector2(0f, 2f),
        new Vector2(-1f, 0f),
    ];

    public bool ShowIFF { get; set; } = true;
    public bool ShowIFFShuttles { get; set; } = true;
    public bool ShowDocks { get; set; } = true;

    public float MaximumIFFDistance { get; set; } = 3000f; // Frontier // Mono - 3000 by default to not gigaclutter
    public bool HideCoords { get; set; } = false; // Frontier

    private static Color _dockLabelColor = Color.White; // Frontier

    /// <summary>
    ///   If present, called for every IFF. Must determine if it should or should not be shown.
    /// </summary>
    public Func<EntityUid, MapGridComponent, IFFComponent?, bool, string, bool>? IFFFilter { get; set; } = null;

    /// <summary>
    /// Raised if the user left-clicks on the radar control with the relevant entitycoordinates.
    /// </summary>
    public Action<EntityCoordinates>? OnRadarClick;

    public Action<EntityUid>? OnPlanetClick;

    private readonly List<(EntityUid Uid, Vector2 Pos, float Radius, bool InRange)> _planetHitboxes = new();

    // CE: hold-to-descend targeting. The pilot must hold the click on a planet for
    // PlanetHoldSeconds before the descend request fires; releasing early cancels.
    public const float PlanetHoldSeconds = 1f;
    private EntityUid? _holdPlanet;
    private TimeSpan _holdStart;

    /// <summary>CE: seconds left on the hold-to-target countdown, null when not targeting.</summary>
    public float? TargetingRemaining { get; private set; }

    private List<Entity<MapGridComponent>> _grids = new();

    // CE: off-layer radar. Grids on maps vertically adjacent to ours (neighbouring
    // z-levels and transit gaps) are drawn ghosted, with an arrow on the distance value.
    private const float OffLayerAlpha = 0.45f; // alpha multiplier at exactly one level of separation
    private const float MinOffLayerAlpha = 0.12f; // distant contacts stay at least this visible
    private readonly List<(EntityUid MapUid, int Dir)> _adjacentZMaps = new();
    private List<Entity<MapGridComponent>> _offLayerGrids = new();
    private readonly List<(Entity<MapGridComponent> Grid, int ZDir)> _drawGrids = new();

    // Mono - set if we want this to detect not from itself
    public List<EntityUid>? Detectors = null;

    #region Mono
    // These 2 handle timing updates
    protected const float RadarUpdateInterval = 0f;
    protected float _updateAccumulator = 0f;

    // doesn't support absolute panning and angle follow, but why would you need that?
    protected bool _relativePanning = false;
    protected bool _angleFollow = true;
    private bool _radarModeDefaultsApplied;

    private bool _wasPanned = false;
    #endregion

    protected bool _isMouseDown;
    protected bool _isMouseInside;
    protected Vector2 _lastMousePos;
    protected float _lastFireTime;
    protected const float FireRateLimit = 0.1f; // 100ms between shots

    private enum RadarAzimuthMode : byte
    {
        Edge,
        Ring,
        Off,
    }

    private BoxContainer? _radarModeButtons;
    private RadarModeButton? _radarAzimuthButton;
    private RadarModeButton? _radarRotationButton;
    private RadarModeButton? _radarAnchorButton;
    private RadarModeButton? _radarResetButton;
    private RadarAzimuthMode _azimuthMode;

    public ShuttleNavControl() : this(64f, 256f, 256f) { } // Mono

    public ShuttleNavControl(float minRange, float maxRange, float range) : base(minRange, maxRange, range) // Mono
    {
        RobustXamlLoader.Load(this);
        _detection = EntManager.System<DetectionSystem>(); // Mono
        _shuttles = EntManager.System<SharedShuttleSystem>();
        _transform = EntManager.System<SharedTransformSystem>();
        _station = EntManager.System<StationSystem>(); // Frontier
        _blips = EntManager.System<RadarBlipsSystem>();
        _zLevels = EntManager.System<CESharedZLevelsSystem>(); // CE

        OnMouseEntered += HandleMouseEntered;
        OnMouseExited += HandleMouseExited;
    }

    private void HandleMouseEntered(GUIMouseHoverEventArgs args)
    {
        _isMouseInside = true;
    }

    private void HandleMouseExited(GUIMouseHoverEventArgs args)
    {
        _isMouseInside = false;
    }

    public void SetMatrix(EntityCoordinates? coordinates, Angle? angle)
    {
        if (_wasPanned) // Mono hack
            return;

        _coordinates = coordinates;
        // Mono - TODO: either remove this or make this do anything
        // _rotation = angle;
    }

    public void SetConsole(EntityUid? consoleEntity)
    {
        if (_consoleEntity == consoleEntity)
            return;

        _consoleEntity = consoleEntity;
        _radarModeDefaultsApplied = false;
        ApplyRadarModeDefaults();
    }

    // converts Offset to world-relative offset so we can modify radar parameters without conversion headaches
    // call this before potentially rotation-modifying operations and PanToEnt() after
    private void PanToWorld()
    {
        if (!_angleFollow || _coordinates is not { } cord)
            return;
        var coordEntRot = _transform.GetWorldRotation(cord.EntityId);
        Offset = coordEntRot.RotateVec(Offset);
    }

    // converts world-relative Offset to relative to current view
    // call this after potentially rotation-modifying operations and PanToWorld() before
    private void PanToEnt()
    {
        if (!_angleFollow || _coordinates is not { } cord)
            return;
        var coordEntRot = _transform.GetWorldRotation(cord.EntityId);
        Offset = (-coordEntRot).RotateVec(Offset);
    }

    // reanchor our view to console or grid
    private void ReanchorView()
    {
        if (_consoleEntity is not { } cons
        || _coordinates is not { } cord
        || !EntManager.TryGetComponent<TransformComponent>(cons, out var xform))
            return;

        PanToWorld();
        var anchTo = cons;
        if (xform.GridUid != null)
            anchTo = xform.GridUid.Value;
        _coordinates = _transform.WithEntityId(cord, anchTo);
        _relativePanning = true;
        PanToEnt();
    }

    private void EnsureRadarModeButtons()
    {
        if (_radarModeButtons != null)
            return;

        if (Parent is not LayoutContainer parent)
            return;

        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

        _radarModeButtons = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 2,
            HorizontalExpand = false,
            VerticalExpand = false,
            MouseFilter = MouseFilterMode.Stop,
        };

        _radarAzimuthButton = CreateRadarModeButton(RadarModeButtonIcon.Azimuth);
        _radarAzimuthButton.ToolTip = Loc.GetString("shuttle-console-button-azimuth");
        _radarAzimuthButton.OnPressed += _ =>
        {
            _azimuthMode = _azimuthMode switch
            {
                RadarAzimuthMode.Edge => RadarAzimuthMode.Ring,
                RadarAzimuthMode.Ring => RadarAzimuthMode.Off,
                _ => RadarAzimuthMode.Edge,
            };
        };

        _radarRotationButton = CreateRadarModeButton(RadarModeButtonIcon.Rotation);
        _radarRotationButton.ToolTip = Loc.GetString("shuttle-console-button-rotation");
        _radarRotationButton.OnPressed += _ =>
        {
            PanToWorld();
            _angleFollow ^= true;
            PanToEnt();
        };

        _radarAnchorButton = CreateRadarModeButton(RadarModeButtonIcon.Anchor);
        _radarAnchorButton.ToolTip = Loc.GetString("shuttle-console-button-anchor");
        _radarAnchorButton.OnPressed += _ =>
        {
            if (_coordinates is not { } cord)
                return;

            // if we're anchored or not yet bound to map, just deanchor
            if (_relativePanning || !EntManager.HasComponent<MapComponent>(cord.EntityId))
            {
                PanToWorld();
                // we're deanchoring, so simply detach our view to the map
                _coordinates = _transform.ToCoordinates(_transform.ToMapCoordinates(cord));
                _relativePanning = false;
                _wasPanned = true;
                PanToEnt();
            }
            else
            {
                ReanchorView();
            }
        };

        _radarResetButton = CreateRadarModeButton(RadarModeButtonIcon.Reset);
        _radarResetButton.ToolTip = Loc.GetString("shuttle-console-button-reset");
        _radarResetButton.OnPressed += _ =>
        {
            _radarModeDefaultsApplied = false;
            ApplyRadarModeDefaults();
            if (EntManager.TryGetComponent<TransformComponent>(_consoleEntity, out var xform))
            {
                Offset = Vector2.Zero;
                _coordinates = xform.Coordinates;
                ReanchorView();
            }
        };

        _radarModeButtons.AddChild(_radarAzimuthButton);
        _radarModeButtons.AddChild(_radarRotationButton);
        _radarModeButtons.AddChild(_radarAnchorButton);
        _radarModeButtons.AddChild(_radarResetButton);

        parent.AddChild(_radarModeButtons);
        LayoutContainer.SetAnchorAndMarginPreset(_radarModeButtons, LayoutContainer.LayoutPreset.BottomLeft, margin: 10);
    }

    private void ApplyRadarModeDefaults()
    {
        if (_radarModeDefaultsApplied)
            return;

        if (!EntManager.TryGetComponent<RadarConsoleComponent>(_consoleEntity, out var radar))
            return;

        _radarModeDefaultsApplied = true;
        Draggable = radar.Pannable;
        _angleFollow = !radar.NoRotate;
        _relativePanning = radar.RelativePanning;
    }

    private static RadarModeButton CreateRadarModeButton(RadarModeButtonIcon icon = RadarModeButtonIcon.None)
    {
        return new RadarModeButton(icon)
        {
            MinWidth = 16f,
            MaxWidth = 16f,
            MinHeight = 16f,
            MaxHeight = 16f,
            HorizontalExpand = false,
            VerticalExpand = false,
            ModulateSelfOverride = Color.White.WithAlpha(0.55f),
        };
    }

    internal enum RadarModeButtonIcon : byte
    {
        None,
        Azimuth,
        Rotation,
        Anchor,
        Reset
    }

    public sealed class RadarModeButton : BaseButton
    {
        private readonly RadarModeButtonIcon _icon;

        internal RadarModeButton(RadarModeButtonIcon icon)
        {
            _icon = icon;
        }

        protected override Vector2 MeasureOverride(Vector2 availableSize)
        {
            return new Vector2(16f, 16f);
        }

        protected override void Draw(DrawingHandleScreen handle)
        {
            var alpha = DrawMode switch
            {
                DrawModeEnum.Pressed => 0.62f,
                DrawModeEnum.Hover => 0.48f,
                _ => 0.32f,
            };

            var center = new Vector2(PixelSize.X * 0.5f, PixelSize.Y * 0.5f);
            var radius = MathF.Min(PixelSize.X, PixelSize.Y) * 0.42f;
            handle.DrawCircle(center, radius, Color.White.WithAlpha(alpha));

            var up = new Vector2(0f, -radius);
            var down = new Vector2(0f, radius);
            var leftOffs = new Vector2(-radius, 0f);
            var rightOffs = new Vector2(radius, 0f);
            var top = center + up;
            var bottom = center + down;
            var left = center + leftOffs;
            var right = center + rightOffs;

            switch (_icon) {
                case RadarModeButtonIcon.Azimuth:
                {
                    var iconColor = Color.Black.WithAlpha(0.95f);
                    var topLeft = center + (up + leftOffs) / MathF.Sqrt(2f);
                    var topRight = center + (up + rightOffs) / MathF.Sqrt(2f);
                    var bottomLeft = center + (down + leftOffs) / MathF.Sqrt(2f);
                    var bottomRight = center + (down + rightOffs) / MathF.Sqrt(2f);

                    handle.DrawLine(topLeft, bottomRight, iconColor);
                    handle.DrawLine(bottomLeft, topRight, iconColor);
                    handle.DrawLine(left, right, iconColor);
                    handle.DrawLine(bottom, top, iconColor);
                    break;
                }
                case RadarModeButtonIcon.Rotation:
                {
                    var iconColor = Color.Yellow.WithAlpha(0.95f);
                    var innerRatio = 0.8f;
                    var segCount = 3;
                    var prevOffs = up * innerRatio;
                    for (var i = 0; i < segCount; i++)
                    {
                        var angle = Angle.FromDegrees(120f * i / (float)segCount - 15f);
                        var thisOffs = angle.RotateVec(up * innerRatio);
                        var thisPointUp = center + thisOffs;
                        var thisPointDown = center - thisOffs;
                        var oldPointUp = center + prevOffs;
                        var oldPointDown = center - prevOffs;
                        handle.DrawLine(oldPointUp, thisPointUp, iconColor);
                        handle.DrawLine(oldPointDown, thisPointDown, iconColor);
                        prevOffs = thisOffs;
                    }
                    break;
                }
                case RadarModeButtonIcon.Anchor:
                {
                    var iconColor = Color.Blue.WithAlpha(0.95f);
                    var stemTop = center + up * 0.5f;
                    var crossLeft = center + leftOffs * 0.3f + up * 0.7f;
                    var crossRight = center + rightOffs * 0.3f + up * 0.7f;;
                    var leftFluke = center + leftOffs * 0.6f + down * 0.6f;
                    var rightFluke = center + rightOffs * 0.6f + down * 0.6f;
                    var innerRadius = radius * 0.4f;
                    var innerTop = center + up * 0.6f;

                    handle.DrawCircle(innerTop, innerRadius, iconColor, false);
                    handle.DrawLine(stemTop, bottom, iconColor);
                    handle.DrawLine(crossLeft, crossRight, iconColor);
                    handle.DrawLine(bottom, leftFluke, iconColor);
                    handle.DrawLine(bottom, rightFluke, iconColor);
                    break;
                }
                case RadarModeButtonIcon.Reset:
                {
                    var iconColor = Color.Red.WithAlpha(0.95f);
                    handle.DrawLine(left, right, iconColor);
                    break;
                }
                default:
                    break;
            }
        }
    }

    // Mono - evil hack
    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);
        if (_isMouseInside)
            _lastMousePos = args.RelativePosition;

        if (!_draggin || _coordinates == null)
            return;

        if (!_relativePanning
            && _coordinates?.EntityId is { } coordEnt
            && EntManager.TryGetComponent<TransformComponent>(coordEnt, out var coordXform)
            && coordXform.MapUid != coordEnt
        )
            _coordinates = _transform.ToCoordinates(_transform.ToMapCoordinates(_coordinates.Value));


        _wasPanned = true;
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        _isMouseDown = true;
        _lastMousePos = args.RelativePosition;

        // CE: begin hold-to-descend targeting if the press landed on a planet.
        if (TryGetHoveredPlanet(args.RelativePosition, out var pressedPlanet, out var inRange))
        {
            // Outside the zone band the click is still swallowed (no stray weapon
            // fire at the blip) but no targeting hold starts.
            if (inRange)
            {
                _holdPlanet = pressedPlanet;
                _holdStart = IoCManager.Resolve<IGameTiming>().CurTime;
            }

            return;
        }

        TryFireAtPosition(args.RelativePosition);
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);

        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        _isMouseDown = false;

        // CE: releasing before the hold completes cancels the targeting.
        if (_holdPlanet != null)
        {
            _holdPlanet = null;
            TargetingRemaining = null;
            return;
        }

        // Clicks on planets are consumed by the hold-to-descend flow above.
        if (TryGetHoveredPlanet(args.RelativePosition, out _))
            return;

        var coords = GetMouseEntityCoordinates(args.RelativePosition);
        OnRadarClick?.Invoke(coords);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _updateAccumulator += args.DeltaSeconds;

        // CE: advance the hold-to-descend targeting countdown; cancel if the cursor
        // slid off the planet or the button was released elsewhere.
        if (_holdPlanet is { } holdPlanet)
        {
            var stillHeld = _isMouseDown && _isMouseInside
                && TryGetHoveredPlanet(_lastMousePos, out var hovered) && hovered == holdPlanet;

            if (!stillHeld)
            {
                _holdPlanet = null;
                TargetingRemaining = null;
            }
            else
            {
                var elapsed = (IoCManager.Resolve<IGameTiming>().CurTime - _holdStart).TotalSeconds;
                var remaining = PlanetHoldSeconds - elapsed;
                if (remaining <= 0)
                {
                    _holdPlanet = null;
                    TargetingRemaining = null;
                    OnPlanetClick?.Invoke(holdPlanet);
                }
                else
                {
                    TargetingRemaining = (float)remaining;
                }
            }
        }

        if (_updateAccumulator >= RadarUpdateInterval)
        {
            _updateAccumulator = 0; // I'm not subtracting because frame updates can majorly lag in a way normal ones cannot.

            if (_consoleEntity != null)
                _blips.RequestBlips((EntityUid)_consoleEntity);
        }

        if (_isMouseDown && _isMouseInside)
        {
            var currentTime = IoCManager.Resolve<IGameTiming>().CurTime.TotalSeconds;
            if (currentTime - _lastFireTime >= FireRateLimit)
            {
                var mousePos = UserInterfaceManager.MousePositionScaled;
                var relativePos = mousePos.Position - GlobalPosition;
                if (relativePos != _lastMousePos)
                {
                    _lastMousePos = relativePos;
                }
                TryFireAtPosition(relativePos);
                _lastFireTime = (float)currentTime;
            }
        }
    }

    private void TryFireAtPosition(Vector2 relativePosition)
    {
        var coords = GetMouseEntityCoordinates(relativePosition);
        OnRadarClick?.Invoke(coords);
    }

    /// <summary>
    /// Gets the entity coordinates of where the mouse position is, relative to the control.
    /// </summary>
    [PublicAPI]
    public EntityCoordinates GetMouseCoordinatesFromCenter()
    {
        if (_coordinates == null || _rotation == null)
        {
            return EntityCoordinates.Invalid;
        }

        var pos = _uiManager.MousePositionScaled.Position - GlobalPosition;
        return GetMouseEntityCoordinates(pos);
    }

    public void UpdateState(NavInterfaceState state)
    {
        EnsureRadarModeButtons();
        ApplyRadarModeDefaults();
        SetMatrix(EntManager.GetCoordinates(state.Coordinates), state.Angle);

        WorldMaxRange = state.MaxRange;

        if (WorldMaxRange < WorldRange)
        {
            ActualRadarRange = WorldMaxRange;
        }

        if (WorldMaxRange < WorldMinRange)
            WorldMinRange = WorldMaxRange;

        ActualRadarRange = Math.Clamp(ActualRadarRange, WorldMinRange, WorldMaxRange);

        // Frontier
        if (state.MaxIffRange != null)
            MaximumIFFDistance = state.MaxIffRange.Value;
        HideCoords = state.HideCoords;
        // End Frontier

        _docks = state.Docks;

        NfUpdateState(state); // Frontier Update State
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        DrawBacking(handle);
        DrawCircles(handle);

        // No data
        if (_coordinates == null || _rotation == null)
        {
            return;
        }

        var xformQuery = EntManager.GetEntityQuery<TransformComponent>();
        var fixturesQuery = EntManager.GetEntityQuery<FixturesComponent>();
        var bodyQuery = EntManager.GetEntityQuery<PhysicsComponent>();

        if (!xformQuery.TryGetComponent(_coordinates.Value.EntityId, out var xform)
            || xform.MapID == MapId.Nullspace)
        {
            return;
        }

        // Mono
        if (EntManager.TryGetComponent<RadarConsoleComponent>(_consoleEntity, out var radar))
        {
            Draggable = radar.Pannable;
        }
        // Mono - TODO: remove _rotation and make it a method instead
        var coordEnt = _coordinates.Value.EntityId;
        var coordEntRot = _transform.GetWorldRotation(coordEnt);
        if (_angleFollow && EntManager.TryGetComponent<TransformComponent>(coordEnt, out var coordXform))
            _rotation = coordEntRot;
        else
            _rotation = Angle.Zero;

        var worldRot = _rotation.Value;
        var mapPos = _transform.ToMapCoordinates(_coordinates.Value).Offset(_rotation.Value.RotateVec(Offset));
        var mapCoord = _transform.ToCoordinates(mapPos);
        var worldToShuttle = Matrix3Helpers.CreateTranslation(-mapCoord.Position) * Matrix3Helpers.CreateRotation(-worldRot);
        Matrix3x2.Invert(worldToShuttle, out var shuttleToWorld);
        var shuttleToView = Matrix3x2.CreateScale(new Vector2(MinimapScale, -MinimapScale)) * Matrix3x2.CreateTranslation(MidPointVector);
        var worldToView = worldToShuttle * shuttleToView;

        // Frontier Corvax: north line drawing
        DrawNorthLine(handle, worldRot);

        // Mono
        switch (_azimuthMode)
        {
            case RadarAzimuthMode.Edge:
                DrawAzimuthScale(handle, worldRot);
                break;
            case RadarAzimuthMode.Ring:
                DrawAzimuthRing(handle, worldRot);
                break;
        }

        if (worldRot != Angle.Zero)
        {
            DrawCompassOverlay(handle, coordEntRot);
        }

        // CE: planets render under grids, shields, docks and blips.
        DrawPlanets(handle, xform.MapID, mapPos.Position, worldToView);

        // Draw shields (over planets, under our grid detail)
        DrawShields(handle, xform, worldToShuttle);

        // Draw our grid in detail
        var ourGridId = xform.GridUid;
        if (EntManager.TryGetComponent<MapGridComponent>(ourGridId, out var ourGrid) &&
            fixturesQuery.HasComponent(ourGridId.Value))
        {
            var ourGridToWorld = _transform.GetWorldMatrix(ourGridId.Value);
            var ourGridToShuttle = Matrix3x2.Multiply(ourGridToWorld, worldToShuttle);
            var ourGridToView = ourGridToShuttle * shuttleToView;
            var color = _shuttles.GetIFFColor(ourGridId.Value, self: true);

            DrawGrid(handle, ourGridToView, (ourGridId.Value, ourGrid), color);
            DrawDocks(handle, ourGridId.Value, ourGridToView);
        }

        // Draw radar position on the station
        // Mono - use precalculated verts and scale each point rather than allocating a fresh array
        var radarPosVerts = new Vector2[RadarPosVertsCache.Length];
        for (var i = 0; i < radarPosVerts.Length; i++)
        {
            radarPosVerts[i] = ScalePosition(RadarPosVertsCache[i]);
        }

        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, radarPosVerts, Color.Lime);

        var viewBounds = new Box2Rotated(new Box2(-WorldRange, -WorldRange, WorldRange, WorldRange).Translated(mapPos.Position), worldRot, mapPos.Position);
        var viewAABB = viewBounds.CalcBoundingBox();

        _grids.Clear();
        _mapManager.FindGridsIntersecting(xform.MapID, new Box2(mapPos.Position - MaxRadarRangeVector, mapPos.Position + MaxRadarRangeVector), ref _grids, approx: true, includeMap: false);

        // CE: gather grids on vertically adjacent maps (neighbouring z-levels and
        // transit gaps). Z-maps share XY coordinate space, so the same query box works.
        _drawGrids.Clear();
        foreach (var sameLayerGrid in _grids)
        {
            _drawGrids.Add((sameLayerGrid, 0));
        }

        _adjacentZMaps.Clear();
        var ourMapUid = _mapManager.GetMapEntityId(xform.MapID);
        if (ourMapUid.IsValid())
            _zLevels.GetAdjacentRenderMaps(ourMapUid, _adjacentZMaps);

        foreach (var (adjMapUid, zMapDir) in _adjacentZMaps)
        {
            if (!EntManager.TryGetComponent(adjMapUid, out MapComponent? adjMapComp))
                continue;

            _offLayerGrids.Clear();
            _mapManager.FindGridsIntersecting(adjMapComp.MapId, new Box2(mapPos.Position - MaxRadarRangeVector, mapPos.Position + MaxRadarRangeVector), ref _offLayerGrids, approx: true, includeMap: false);

            foreach (var offGrid in _offLayerGrids)
            {
                _drawGrids.Add((offGrid, zMapDir));
            }
        }
        // CE: viewer's continuous altitude (level depth + transit progress + airborne
        // offset) so off-layer ghosting can fade with actual vertical separation.
        var ourAltitude = _zLevels.GetAbsoluteAltitude(coordEnt);
        // End CE

        // Mono edited: Frontier - collect blip location data outside foreach - more changes ahead
        _tempBlipDataList.Clear();

        _visibleGridsSet.Clear();

        // Draw other grids... differently
        foreach (var (grid, zDir) in _drawGrids) // CE: zDir != 0 = grid is on an adjacent z-map
        {
            var gUid = grid.Owner;
            if (gUid == ourGridId || !fixturesQuery.HasComponent(gUid))
                continue;

            var gridBody = bodyQuery.GetComponent(gUid);
            EntManager.TryGetComponent<IFFComponent>(gUid, out var iff);

            if (!_shuttles.CanDraw(gUid, gridBody, iff))
                continue;

            var hideLabel = iff != null && (iff.Flags & IFFFlags.HideLabel) != 0x0;
            var noLabel = iff != null && (iff.Flags & IFFFlags.HideLabelAlways) != 0x0;
            var detectionLevel = _consoleEntity == null ? DetectionLevel.Detected : GetGridDetected(grid.Owner);
            var detected = detectionLevel != DetectionLevel.Undetected || !hideLabel;
            var blipOnly = detectionLevel != DetectionLevel.Detected; // don't show outline outside of detection radius even if IFF on
            if (!detected)
                continue;

            if (!blipOnly && zDir == 0) // CE: off-layer grids aren't selectable
                _visibleGridsSet.Add(grid);
            var curGridToWorld = _transform.GetWorldMatrix(gUid);
            var curGridToView = curGridToWorld * worldToView;

            var hideColor = hideLabel && iff != null && (iff.Flags & IFFFlags.AlwaysShowColor) == 0x0;
            var labelColor = hideColor ? blipOnly ? Color.Orange : Color.White : _shuttles.GetIFFColor(grid, self: false, iff);

            // CE: ghost anything that isn't on our layer so it's obviously not
            // co-planar, fading with the actual vertical separation: a ship mid-transit
            // (or climbing within its level) is brighter than one a full level away,
            // and two levels away is dimmer still.
            var offLayerAlpha = 1f;
            if (zDir != 0)
            {
                var zDist = MathF.Abs(_zLevels.GetAbsoluteAltitude(gUid) - ourAltitude);
                offLayerAlpha = Math.Clamp(MathF.Pow(OffLayerAlpha, zDist), MinOffLayerAlpha, 1f);
                labelColor = labelColor.WithAlpha(labelColor.A * offLayerAlpha);
            }

            var coordColor = new Color(labelColor.R * 0.8f, labelColor.G * 0.8f, labelColor.B * 0.8f, labelColor.A * 0.5f); // CE: inherit ghost alpha

            var isPlayerShuttle = iff != null && (iff.Flags & IFFFlags.IsPlayerShuttle) != 0x0;
            // Others default:
            // Color.FromHex("#FFC000FF")
            // Hostile default: Color.Firebrick
            // Mono
            var labelName = noLabel ? null : hideLabel ?
                detectionLevel == DetectionLevel.PartialDetected ?
                    Loc.GetString($"shuttle-console-signature-infrared")
                    : _detection.HandleUnknownMassLabel(grid.Owner)
                : _shuttles.GetIFFLabel(grid, self: false, component: iff);

            var shouldDrawIFF = ShowIFF && labelName != null;
            if (shouldDrawIFF)
            {
                if (IFFFilter != null)
                    shouldDrawIFF &= IFFFilter(gUid, grid.Comp, iff, hideLabel, labelName!);
                if (isPlayerShuttle)
                    shouldDrawIFF &= ShowIFFShuttles;
            }

            //var mapCenter = curGridToWorld. * gridBody.LocalCenter;
            //shouldDrawIFF = NfCheckShouldDrawIffRangeCondition(shouldDrawIFF, mapCenter, curGridToWorld); // Frontier code
            // Frontier: range checks // Mono
            var gridMapPos = _transform.ToMapCoordinates(new EntityCoordinates(gUid, gridBody.LocalCenter)).Position;
            if (!hideLabel) // Mono - show thermal signatures even at long range
                shouldDrawIFF = NfCheckShouldDrawIffRangeCondition(shouldDrawIFF, mapPos.Position - gridMapPos);
            // End Frontier

            // Mono
            var gridUiPosition = Vector2.Transform(gridBody.LocalCenter, curGridToView) / UIScale;

            if (shouldDrawIFF)
            {
                //var gridCentre = Vector2.Transform(gridBody.LocalCenter, curGridToView);
                //gridCentre.Y = -gridCentre.Y;

                // Frontier: IFF drawing functions
                // The actual position in the UI. We offset the matrix position to render it off by half its width
                // plus by the offset.
                //var uiPosition = ScalePosition(gridCentre) / UIScale;
                var uiPosition = gridUiPosition; // Mono

                // Confines the UI position within the viewport.
                var uiXCentre = (int)Width / 2;
                var uiYCentre = (int)Height / 2;
                var uiXOffset = uiPosition.X - uiXCentre;
                var uiYOffset = uiPosition.Y - uiYCentre;
                var uiDistance = (int)Math.Sqrt(Math.Pow(uiXOffset, 2) + Math.Pow(uiYOffset, 2));
                var uiX = uiXCentre * uiXOffset / uiDistance;
                var uiY = uiYCentre * uiYOffset / uiDistance;

                var isOutsideRadarCircle = uiDistance > Math.Abs(uiX) && uiDistance > Math.Abs(uiY);
                if (isOutsideRadarCircle)
                {
                    // 0.95f for offsetting the icons slightly away from edge of radar so it doesnt clip.
                    uiX = uiXCentre * uiXOffset / uiDistance * 0.95f;
                    uiY = uiYCentre * uiYOffset / uiDistance * 0.95f;
                    uiPosition = new Vector2(
                        x: uiX + uiXCentre,
                        y: uiY + uiYCentre
                    );
                }

                var scaledMousePosition = GetMouseCoordinatesFromCenter().Position * UIScale;
                var isMouseOver = Vector2.Distance(scaledMousePosition, uiPosition * UIScale) < 30f;

                // Distant stations that are not player controlled ships
                var isDistantPOI = iff != null || (iff == null || (iff.Flags & IFFFlags.IsPlayerShuttle) == 0x0);

                var distance = Vector2.Distance(gridMapPos, mapPos.Position);

                if (!isOutsideRadarCircle || isDistantPOI || isMouseOver)
                {
                    // Shows decimal when distance is < 50m, otherwise pointless to show it.
                    var displayedDistance = distance < 50f ? $"{distance:0.0}" : distance < 1000 ? $"{distance:0}" : $"{distance / 1000:0.0}k";

                    // CE: mark off-layer contacts on the distance value; the planar
                    // distance still reads fine since z-maps share XY space. One
                    // arrow per level of separation ("↑↑" = two levels up).
                    if (zDir != 0)
                        displayedDistance = new string(zDir > 0 ? '↑' : '↓', Math.Min(Math.Abs(zDir), 3)) + displayedDistance;

                    var labelText = Loc.GetString("shuttle-console-iff-label", ("name", labelName)!, ("distance", displayedDistance));

                    var coordsText = $"({gridMapPos.X:0.0}, {gridMapPos.Y:0.0})";

                    #region Mono

                    // Why are the magic numbers 0.9 and 0.7 used? I have no fucking clue.
                    var labelDimensions = handle.GetDimensions(Font, labelText, 0.9f);
                    var blipSize = RadarBlipSize * 0.7f;

                    // The center of the radar in UI space.
                    var uiCenter = new Vector2(Width * 0.5f, Height * 0.5f);

                    // Whether the blip is on the left side of the center of the radar.
                    var isOnLeftSide = (uiPosition - uiCenter).X < 0;

                    // The UI position of the bottom-left corner of the label, relative to the UI center of the radar, when the label is right-aligned.
                    var labelPosition = uiPosition + new Vector2(-labelDimensions.X - blipSize, -labelDimensions.Y * 0.5f) - uiCenter;

                    // The bounds corners of the label, relative to labelPosition.
                    var labelCorners = new Vector2[] {
                        labelPosition,
                        labelPosition + new Vector2(labelDimensions.X, 0),
                        labelPosition + new Vector2(0, labelDimensions.Y),
                        labelPosition + labelDimensions
                    };

                    // The radius and squared radius of the radar, in virtual pixels.
                    var radius = Width * 0.5f;
                    var squaredRadius = radius * radius;

                    // If true, flip the entire label to the right side of the blip and left-align it.
                    // We default to the label being on the left side of the blip because it looked better to me in testing. (arbitrary)
                    var flipLabel = isOnLeftSide && labelCorners.Any(corner => corner.LengthSquared() > squaredRadius);

                    // Calculate unscaled offsets.
                    var labelOffset = new Vector2()
                    {
                        X = flipLabel
                            ? blipSize // Label on the right side of the blip, left-aligned text.
                            : -labelDimensions.X - blipSize, // Label on the left side of the blip, right-aligned text.
                        Y = -labelDimensions.Y * 0.5f
                    };

                    #endregion Mono

                    // Get company color if entity has CompanyComponent
                    var displayColor = labelColor;
                    if (!hideLabel && EntManager.TryGetComponent(gUid, out Shared._Mono.Company.CompanyComponent? companyComp) &&
                        !string.IsNullOrEmpty(companyComp.CompanyName))
                    {
                        var prototypeManager = IoCManager.Resolve<IPrototypeManager>();
                        CompanyPrototype? prototype = null;
                        if (prototypeManager.TryIndex(companyComp.CompanyName, out prototype) && prototype != null)
                        {
                            displayColor = prototype.Color;

                            // CE: company colours are opaque; re-apply the off-layer ghosting.
                            if (zDir != 0)
                                displayColor = displayColor.WithAlpha(displayColor.A * offLayerAlpha);
                        }
                    }

                    // Split label text into lines
                    var lines = labelText.Split('\n');
                    var mainLabel = lines[0];

                    // Draw main ship label with company color if available
                    handle.DrawString(Font, (uiPosition + labelOffset) * UIScale, mainLabel, UIScale * 0.9f, displayColor);

                    // Draw company label if present
                    if (!hideLabel && lines.Length > 1)
                    {
                        var companyLabel = lines[1];
                        var companyLabelOffset = new Vector2(
                            labelOffset.X,
                            labelOffset.Y + handle.GetDimensions(Font, mainLabel, 0.9f).Y
                        );

                        handle.DrawString(Font, (uiPosition + companyLabelOffset) * UIScale, companyLabel, UIScale * 0.9f, displayColor);
                    }

                    if (isMouseOver && !HideCoords)
                    {
                        var coordDimensions = handle.GetDimensions(Font, coordsText, 0.7f);
                        var coordOffset = new Vector2()
                        {
                            X = uiPosition.X > Width / 2f
                                ? -coordDimensions.X - blipSize / 0.7f // right align the text to left of the blip (0.7 needed for scale)
                                : blipSize, // left align the text to the right of the blip
                            Y = labelOffset.Y + handle.GetDimensions(Font, mainLabel, 1f).Y + (lines.Length > 1 ? handle.GetDimensions(Font, lines[1], 1f).Y : 0) + 5
                        };
                        handle.DrawString(Font, (uiPosition + coordOffset) * UIScale, coordsText, 0.7f * UIScale, displayColor);
                    }
                }

                NfAddBlipToList(_tempBlipDataList, isOutsideRadarCircle, uiPosition, uiXCentre, uiYCentre, labelColor, hideLabel ? default : gUid); // Frontier code
                // End Frontier: IFF drawing functions
            }

            // Frontier Don't skip drawing blips if they're out of range.
            NfDrawBlips(handle, _tempBlipDataList);

            // Detailed view
            var gridAABB = curGridToWorld.TransformBox(grid.Comp.LocalAABB);

            // Skip drawing if it's out of range.
            if (!gridAABB.Intersects(viewAABB))
                continue;

            // Mono
            if (!blipOnly)
            {
                DrawGrid(handle, curGridToView, grid, labelColor);

                if (zDir == 0) // CE: dock markers are meaningless a level up/down
                    DrawDocks(handle, gUid, curGridToView);
            }
        }

        // If we've set the controlling console, and it's on a different grid
        // to the shuttle itself, then draw an additional marker to help the
        // player determine where they are relative to the shuttle.
        if (_consoleEntity != null && xformQuery.TryGetComponent(_consoleEntity, out var consoleXform))
        {
            if (consoleXform.ParentUid != _coordinates.Value.EntityId)
            {
                var consolePositionWorld = _transform.GetWorldPosition((EntityUid)_consoleEntity);
                var p = Vector2.Transform(consolePositionWorld, worldToView);
                handle.DrawCircle(p, 5, Color.ToSrgb(Color.Cyan), true);
            }
        }

        #region Mono
        // Draw radar line
        // First, figure out which angle to draw.
        var updateRatio = _updateAccumulator / RadarUpdateInterval;

        Angle angle = updateRatio * Math.Tau;
        var origin = ScalePosition(-new Vector2(Offset.X, -Offset.Y));
        handle.DrawLine(origin, origin + angle.ToVec() * ScaledMinimapRadius * 1.42f, Color.Red.WithAlpha(0.1f));

        // Get blips
        var rawBlips = _blips.GetCurrentBlips();

        // Prepare view bounds for culling
        var monoViewBounds = new Box2(-3f, -3f, PixelSize.X + 3f, PixelSize.Y + 3f);

        // Draw blips using the same grid-relative transformation approach as docks
        foreach (var blip in rawBlips)
        {
            var position = Vector2.Transform(_transform.ToMapCoordinates(blip.Position).Position, worldToView);
            var color = blip.Config.Color.WithAlpha(0.8f);
            var box = new Box2Rotated(blip.Config.Bounds, 0);
            if (blip.Config.RespectZoom)
                box.Box = new Box2(box.Box.BottomLeft * MinimapScale, box.Box.TopRight * MinimapScale);
            if (blip.Config.Rotate)
                box.Rotation = worldRot - blip.Rotation;

            if (blip.GridUid is { } grid)
            {
                // check detection if we're on a grid and that grid isn't our grid
                if (!_visibleGridsSet.Contains(grid) && grid != ourGridId)
                    continue;
            }

            // Check if this blip is within view bounds before drawing
            if (monoViewBounds.Contains(position))
            {
                DrawBlipShape(handle, position, box, color, blip.Config.Shape);
            }
        }

        // Draw hitscan lines from the radar blips system
        var hitscanLines = _blips.GetHitscanLines();
        foreach (var line in hitscanLines)
        {
            var startPosInView = Vector2.Transform(line.Start, worldToView);
            var endPosInView = Vector2.Transform(line.End, worldToView);

            // Only draw lines if at least one endpoint is within view
            if (monoViewBounds.Contains(startPosInView) || monoViewBounds.Contains(endPosInView))
            {
                // Draw the line with the specified thickness and color
                handle.DrawLine(startPosInView, endPosInView, line.Color);

                // For thicker lines, draw multiple lines side by side
                if (line.Thickness > 1.0f)
                {
                    // Calculate perpendicular vector for thickness
                    var dir = (endPosInView - startPosInView).Normalized();
                    var perpendicular = new Vector2(-dir.Y, dir.X) * 0.5f;

                    // Draw additional lines for thickness
                    for (float i = 1; i <= line.Thickness; i += 1.0f)
                    {
                        var offset = perpendicular * i;
                        handle.DrawLine(startPosInView + offset, endPosInView + offset, line.Color);
                        handle.DrawLine(startPosInView - offset, endPosInView - offset, line.Color);
                    }
                }
            }
        }
        #endregion
    }

    protected DetectionLevel GetGridDetected(EntityUid grid)
    {
        if (Detectors != null)
            return _detection.IsGridDetected(grid, Detectors);

        return _consoleEntity == null ? DetectionLevel.Undetected : _detection.IsGridDetected(grid, _consoleEntity.Value);
    }

    private (Vector2 Top, Vector2 Left, Vector2 Offset) GetSize(Box2Rotated bounds)
    {
        var top = (bounds.TopLeft + bounds.TopRight) * 0.5f;
        var left = (bounds.TopLeft + bounds.BottomLeft) * 0.5f;
        var offset = (bounds.TopRight + bounds.BottomLeft) * 0.5f;

        return (top - offset, left - offset, offset);
    }

    private void DrawBlipShape(DrawingHandleScreen handle, Vector2 position, Box2Rotated bounds, Color color, RadarBlipShape shape)
    {
        switch (shape)
        {
            case RadarBlipShape.Circle:
                DrawCircle(handle, position, bounds, color);
                break;
            case RadarBlipShape.Square:
                var boxPoints = new Vector2[]
                {
                    position + bounds.TopLeft,
                    position + bounds.TopRight,
                    position + bounds.BottomRight,
                    position + bounds.BottomLeft
                };
                handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, boxPoints, color);
                break;
            case RadarBlipShape.Triangle:
                var points = new Vector2[]
                {
                    position + bounds.Origin + bounds.Rotation.RotateVec((bounds.TopLeft + bounds.TopRight) * 0.5f - bounds.Origin),
                    position + bounds.BottomLeft,
                    position + bounds.BottomRight
                };
                handle.DrawPrimitives(DrawPrimitiveTopology.TriangleList, points, color);
                break;
            case RadarBlipShape.Star:
                DrawStar(handle, position, bounds, color);
                break;
            case RadarBlipShape.Diamond:
                var size = GetSize(bounds);
                var diamondPoints = new Vector2[]
                {
                    position + size.Offset + size.Top,
                    position + size.Offset + size.Left,
                    position + size.Offset - size.Top,
                    position + size.Offset - size.Left
                };
                handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, diamondPoints, color);
                break;
            case RadarBlipShape.Hexagon:
                DrawHexagon(handle, position, bounds, color);
                break;
            case RadarBlipShape.Arrow:
                DrawArrow(handle, position, bounds, color);
                break;
        }
    }

    private void DrawCircle(DrawingHandleScreen handle, Vector2 position, Box2Rotated bounds, Color color)
    {
        const int segments = 64;
        var buffer = new Vector2[segments + 1];
        var size = GetSize(bounds);
        var offsetPos = position + size.Offset;

        for (var i = 0; i <= segments; i++)
        {
            var angle = i * MathF.Tau / segments;
            var pos = size.Left * MathF.Sin(angle) + size.Top * MathF.Cos(angle);

            buffer[i] = offsetPos + pos;
        }

        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, buffer, color);
    }

    private void DrawStar(DrawingHandleScreen handle, Vector2 position, Box2Rotated bounds, Color color)
    {
        const int points = 5;
        const float innerRatio = 0.4f;
        var vertices = new Vector2[points * 2];
        var size = GetSize(bounds);
        var offsetPos = position + size.Offset;

        for (var i = 0; i < points * 2; i++)
        {
            var angle = i * MathF.PI / points;
            var radius = i % 2 == 0 ? 1f : innerRatio;
            vertices[i] = offsetPos + radius * MathF.Sin(angle) * size.Left - radius * MathF.Cos(angle) * size.Top;
        }

        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, vertices, color);
    }

    private void DrawHexagon(DrawingHandleScreen handle, Vector2 position, Box2Rotated bounds, Color color)
    {
        var vertices = new Vector2[6];
        var size = GetSize(bounds);
        var offsetPos = position + size.Offset;

        for (var i = 0; i < 6; i++)
        {
            var angle = i * MathF.PI / 3;
            vertices[i] = offsetPos + MathF.Sin(angle) * size.Top - MathF.Cos(angle) * size.Left;
        }

        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, vertices, color);
    }

    private void DrawArrow(DrawingHandleScreen handle, Vector2 position, Box2Rotated bounds, Color color)
    {
        var size = GetSize(bounds);
        var offsetPos = position + size.Offset;

        var vertices = new Vector2[]
        {
            offsetPos - size.Top,                    // Tip
            offsetPos + size.Left + size.Top * 0.5f, // Left wing
            offsetPos + size.Top,                    // Bottom
            offsetPos - size.Left + size.Top * 0.5f  // Right wing
        };

        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, vertices, color);
    }

    private void DrawDocks(DrawingHandleScreen handle, EntityUid uid, Matrix3x2 gridToView)
    {
        if (!ShowDocks)
            return;

        const float DockScale = 0.6f;
        var nent = EntManager.GetNetEntity(uid);

        const float sqrt2 = 1.41421356f;
        const float dockRadius = DockScale * sqrt2;
        // Worst-case bounds used to cull a dock:
        Box2 viewBounds = new Box2(-dockRadius, -dockRadius, PixelSize.X + dockRadius, PixelSize.Y + dockRadius); // Frontier: Size<PixelSize
        if (_docks.TryGetValue(nent, out var docks))
        {
            foreach (var state in docks)
            {
                var position = state.Coordinates.Position;

                var positionInView = Vector2.Transform(position, gridToView);
                if (!viewBounds.Contains(positionInView))
                {
                    continue;
                }

                //var color = Color.ToSrgb(Color.Magenta); // Frontier
                var color = Color.ToSrgb(state.HighlightedRadarColor); // Frontier

                var verts = new[]
                {
                    Vector2.Transform(position + new Vector2(-DockScale, -DockScale), gridToView),
                    Vector2.Transform(position + new Vector2(DockScale, -DockScale), gridToView),
                    Vector2.Transform(position + new Vector2(DockScale, DockScale), gridToView),
                    Vector2.Transform(position + new Vector2(-DockScale, DockScale), gridToView),
                };

                handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, verts, color.WithAlpha(0.8f));
                handle.DrawPrimitives(DrawPrimitiveTopology.LineStrip, verts, color);
            }

            // Frontier: draw dock labels (done last to appear on top of all docks, still fights with other grids)
            var labeled = new HashSet<string>();
            foreach (var state in docks)
            {
                if (state.LabelName == null || labeled.Contains(state.LabelName))
                    continue;

                var position = state.Coordinates.Position;
                var uiPosition = Vector2.Transform(position, gridToView);

                if (!viewBounds.Contains(uiPosition))
                    continue;

                labeled.Add(state.LabelName);
                var labelDimensions = handle.GetDimensions(Font, state.LabelName, 0.9f);
                handle.DrawString(Font, (uiPosition / UIScale - labelDimensions / 2) * UIScale, state.LabelName, UIScale * 0.9f, _dockLabelColor);
            }
            // End Frontier
        }
    }

    protected Vector2 InverseScalePosition(Vector2 value)
    {
        var scaledValue = value * UIScale;
        return (scaledValue - MidPointVector) / MinimapScale;
    }

    // Mono
    protected EntityCoordinates GetMouseEntityCoordinates(Vector2 relativePosition)
    {
        if (_coordinates is not { } cord || _rotation is not { } rot)
            return new();

        // multiply by UIScale because UI is Very Intelligent and doesn't scale mouse position for whatever reason
        var screenRelativeWorldPos = InverseMapPosition(relativePosition * UIScale);
        var relativeWorldPos = rot.RotateVec(screenRelativeWorldPos);
        var coordEntRot = _transform.GetWorldRotation(cord.EntityId);
        var coords = cord.Offset((-coordEntRot).RotateVec(relativeWorldPos));
        return coords;
    }

    public class BlipData
    {
        public bool IsOutsideRadarCircle { get; set; }
        public Vector2 UiPosition { get; set; }
        public Vector2 VectorToPosition { get; set; }
        public Color Color { get; set; }
    }

    private const int RadarBlipSize = 15;
    private const int RadarFontSize = 8;

    private void DrawPlanets(DrawingHandleScreen handle, MapId mapId, Vector2 mapPos, Matrix3x2 worldToView)
    {
        _planetHitboxes.Clear();

        // CE: descent spinup state, for the progress ring around the target planet.
        EntityUid? spinupTarget = null;
        var spinupProgress = 0f;
        if (_coordinates != null
            && EntManager.TryGetComponent<TransformComponent>(_coordinates.Value.EntityId, out var coordXform)
            && EntManager.TryGetComponent<CEDescentSpinupComponent>(coordXform.GridUid, out var spinup))
        {
            spinupTarget = spinup.Planet;
            var duration = (spinup.End - spinup.Start).TotalSeconds;
            var elapsed = (IoCManager.Resolve<IGameTiming>().CurTime - spinup.Start).TotalSeconds;
            spinupProgress = duration > 0 ? Math.Clamp((float)(elapsed / duration), 0f, 1f) : 1f;
        }

        var blips = new List<BlipData>();
        var query = EntManager.AllEntityQueryEnumerator<CEPlanetComponent, TransformComponent>();
        while (query.MoveNext(out var uid, out var planet, out var pXform))
        {
            if (pXform.MapID != mapId)
                continue;

            var worldPos = _transform.GetWorldPosition(uid);
            var uiPosition = Vector2.Transform(worldPos, worldToView) / UIScale;
            var color = planet.ZoneColor.WithAlpha(0.9f);

            // CE: descents only lock inside the zone band, so the hold-to-target UX
            // follows the same radius the shared validation checks.
            var inRange = (worldPos - mapPos).Length() <= planet.ZoneRadius;

            var uiXCentre = (int)Width / 2;
            var uiYCentre = (int)Height / 2;
            var uiXOffset = uiPosition.X - uiXCentre;
            var uiYOffset = uiPosition.Y - uiYCentre;
            var uiDistance = (int)Math.Sqrt(Math.Pow(uiXOffset, 2) + Math.Pow(uiYOffset, 2));
            var uiX = uiDistance > 0 ? uiXCentre * uiXOffset / uiDistance : 0;
            var uiY = uiDistance > 0 ? uiYCentre * uiYOffset / uiDistance : 0;

            var isOutsideRadarCircle = uiDistance > Math.Abs(uiX) && uiDistance > Math.Abs(uiY);
            float hitRadius;
            if (isOutsideRadarCircle)
            {
                uiPosition = new Vector2(
                    uiXCentre * uiXOffset / uiDistance * 0.95f + uiXCentre,
                    uiYCentre * uiYOffset / uiDistance * 0.95f + uiYCentre);

                NfAddBlipToList(blips, true, uiPosition, uiXCentre, uiYCentre, color);
                hitRadius = RadarBlipSize * 0.6f;
            }
            else
            {
                // CE: the disc is world-sized (see below), so the hitbox tracks it — floored so a
                // far-zoomed-out planet stays clickable.
                hitRadius = MathF.Max(planet.ZoneRadius * MinimapScale / UIScale, 6f);
            }

            _planetHitboxes.Add((uid, uiPosition, hitRadius, inRange));
            var hovered = _isMouseInside && (_lastMousePos - uiPosition).Length() <= hitRadius;

            var labelOffsetY = RadarBlipSize * 0.5f + 2f;
            if (!isOutsideRadarCircle)
            {
                // CE: world-space size — the disc covers the planet's YML zone (ZoneRadius, the
                // "you are at the planet" band), so it scales with the radar's range/zoom instead
                // of sitting at a fixed pixel size.
                var radius = planet.ZoneRadius * MinimapScale;
                // CE: outline-only, like every other radar element. The band thickness is
                // inset INWARD so the outer edge stays exactly at the zone radius.
                var rimThickness = MathF.Max(3f * UIScale, 1.5f);
                DrawRing(handle, uiPosition * UIScale, radius, rimThickness, color);
                labelOffsetY = radius / UIScale + 4f;
            }

            if (hovered)
            {
                // CE: out-of-range planets can't be targeted — tint the hover ring as a refusal.
                var hoverColor = inRange ? Color.White.WithAlpha(0.8f) : Color.Red.WithAlpha(0.5f);
                DrawRing(handle, uiPosition * UIScale, (hitRadius + 3f) * UIScale, MathF.Max(UIScale, 1f), hoverColor);
            }

            // CE: hold-to-descend targeting progress ring.
            if (_holdPlanet == uid && TargetingRemaining is { } targetingLeft)
            {
                var holdRadius = (hitRadius + 5f) * UIScale;
                var holdProgress = 1f - targetingLeft / PlanetHoldSeconds;
                DrawRing(handle, uiPosition * UIScale, holdRadius, MathF.Max(UIScale, 1f), Color.White.WithAlpha(0.15f));
                DrawProgressArc(handle, uiPosition * UIScale, holdRadius, holdProgress, Color.Cyan);
            }

            // CE: descent spinup progress ring — green and a bit larger than the
            // targeting ring (drawn twice for a thicker line).
            if (spinupTarget == uid)
            {
                var ringRadius = (hitRadius + 8f) * UIScale;
                DrawRing(handle, uiPosition * UIScale, ringRadius, MathF.Max(UIScale, 1f), Color.LimeGreen.WithAlpha(0.15f));
                DrawProgressArc(handle, uiPosition * UIScale, ringRadius, spinupProgress, Color.LimeGreen);
                DrawProgressArc(handle, uiPosition * UIScale, ringRadius + 1f, spinupProgress, Color.LimeGreen);
            }

            if (!ShowIFF)
                continue;

            var distance = (worldPos - mapPos).Length();
            var displayedDistance = distance < 50f ? $"{distance:0.0}" : distance < 1000 ? $"{distance:0}" : $"{distance / 1000:0.0}k";
            var name = EntManager.GetComponent<MetaDataComponent>(uid).EntityName;
            var label = Loc.GetString("shuttle-console-iff-label", ("name", name), ("distance", displayedDistance));
            var labelDims = handle.GetDimensions(Font, label, 0.9f);
            var labelPos = uiPosition + new Vector2(-labelDims.X * 0.5f, labelOffsetY);
            handle.DrawString(Font, labelPos * UIScale, label, UIScale * 0.9f, hovered ? Color.White : color);
        }

        NfDrawBlips(handle, blips);
    }

    /// <summary>
    /// CE: draws an unfilled ring as a filled annulus (triangle strip between the outer
    /// and inner circle). Line-based rings (<see cref="DrawingHandleScreen.DrawCircle"/>
    /// with filled=false, or a closed LineStrip) leave seams/notches where segments join;
    /// a solid band cannot.
    /// </summary>
    private static void DrawRing(DrawingHandleScreen handle, Vector2 center, float radius, float thickness, Color color)
    {
        if (radius <= 0f)
            return;

        var inner = Math.Max(radius - thickness, 0f);
        // Segment count scales with radius so big rings stay round, small ones stay cheap.
        var segments = Math.Clamp((int)(radius * 0.75f), 24, 128);
        var verts = new Vector2[(segments + 1) * 2];
        for (var i = 0; i <= segments; i++)
        {
            // i % segments: the final pair reuses the first angle exactly, so the strip
            // closes on identical vertices — no seam.
            var angle = MathF.Tau * (i % segments) / segments;
            var dir = new Vector2(MathF.Cos(angle), MathF.Sin(angle));
            verts[i * 2] = center + dir * radius;
            verts[i * 2 + 1] = center + dir * inner;
        }

        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleStrip, verts, color);
    }

    /// <summary>CE: draws a clockwise progress arc starting at 12 o'clock.</summary>
    private static void DrawProgressArc(DrawingHandleScreen handle, Vector2 center, float radius, float progress, Color color)
    {
        progress = Math.Clamp(progress, 0f, 1f);
        if (progress <= 0f)
            return;

        var segments = Math.Max(2, (int)(64 * progress));
        var verts = new Vector2[segments + 1];
        const float start = -MathF.PI / 2f;
        for (var i = 0; i <= segments; i++)
        {
            var angle = start + MathF.Tau * progress * i / segments;
            verts[i] = center + new Vector2(MathF.Cos(angle), MathF.Sin(angle)) * radius;
        }

        handle.DrawPrimitives(DrawPrimitiveTopology.LineStrip, verts, color);
    }

    private bool TryGetHoveredPlanet(Vector2 relativePos, out EntityUid planet)
        => TryGetHoveredPlanet(relativePos, out planet, out _);

    private bool TryGetHoveredPlanet(Vector2 relativePos, out EntityUid planet, out bool inRange)
    {
        foreach (var (uid, pos, radius, ranged) in _planetHitboxes)
        {
            if ((relativePos - pos).Length() > radius)
                continue;

            planet = uid;
            inRange = ranged;
            return true;
        }

        planet = default;
        inRange = false;
        return false;
    }

    private void DrawShields(DrawingHandleScreen handle, TransformComponent consoleXform, Matrix3x2 matrix)
    {
        var shields = EntManager.AllEntityQueryEnumerator<ShipShieldVisualsComponent, FixturesComponent, TransformComponent>();
        while (shields.MoveNext(out var uid, out var visuals, out var fixtures, out var xform))
        {
            if (!EntManager.TryGetComponent<TransformComponent>(xform.GridUid, out var parentXform))
                continue;

            if (xform.MapID != consoleXform.MapID)
                continue;

            // Don't draw shields when in FTL
            if (EntManager.HasComponent<FTLComponent>(parentXform.Owner))
                continue;

            var detectionLevel = _consoleEntity == null ? DetectionLevel.Detected : GetGridDetected(parentXform.Owner);
            if (detectionLevel != DetectionLevel.Detected)
                continue;

            var shieldFixture = fixtures.Fixtures.TryGetValue("shield", out var fixture) ? fixture : null;

            if (shieldFixture == null || shieldFixture.Shape is not ChainShape)
                continue;

            ChainShape chain = (ChainShape) shieldFixture.Shape;

            var count = chain.Count;
            var verticies = chain.Vertices;

            var center = _transform.WithEntityId(xform.Coordinates, xform.GridUid.Value).Position;

            for (int i = 1; i < count; i++)
            {
                var v1 = Vector2.Add(center, verticies[i - 1]);
                v1 = Vector2.Transform(v1, parentXform.WorldMatrix); // transform to world matrix
                v1 = Vector2.Transform(v1, matrix); // get back to local matrix for drawing
                v1.Y = -v1.Y;
                v1 = ScalePosition(v1);
                var v2 = Vector2.Add(center, verticies[i]);
                v2 = Vector2.Transform(v2, parentXform.WorldMatrix);
                v2 = Vector2.Transform(v2, matrix);
                v2.Y = -v2.Y;
                v2 = ScalePosition(v2);
                handle.DrawLine(v1, v2, visuals.ShieldColor);
            }
        }
    }
}
