using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ErisWS.DEM.UI;

[GenerateTypedNameReferences]
public sealed partial class DEMConsoleWindow : FancyWindow
{
    public DEMConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
